"""Status action enablement and disabled-reason tables."""

from __future__ import annotations

from typing import Any


def build_action_enabled(
    owner: Any,
    *,
    has_image: bool,
    has_annotations: bool,
    has_suggestions: bool,
    has_writable_context: bool,
    roi_defined: bool,
    selection_count: int,
    can_assist: bool,
    can_review: bool,
    can_export_annotations: bool,
    can_measure: bool,
    has_qc: bool,
) -> dict[str, bool]:
    """Build the action-enabled map for the current status snapshot."""
    return {
        "load_ann_current_act": has_image, "load_ann_multi_act": True,
        "load_ann_all_act": has_image, "reload_ann_act": has_image,
        "save_proj_act": has_image, "load_proj_act": True,
        "save_csv_act": can_export_annotations, "save_json_act": can_export_annotations,
        "export_view_act": has_image, "copy_display_act": has_image,
        "measure_act": can_measure, "clear_roi_act": roi_defined,
        "copy_roi_to_all_act": roi_defined, "save_roi_template_act": roi_defined,
        "apply_roi_template_act": has_image, "suggest_points_act": can_assist,
        "suggest_points_image_act": can_assist, "select_suggestion_strategy_act": has_image,
        "load_suggestion_rule_config_act": has_image, "set_suggestion_score_threshold_act": has_image,
        "accept_visible_suggestions_act": has_suggestions and has_writable_context,
        "accept_green_suggestions_act": has_suggestions and has_writable_context,
        "accept_suggestions_in_roi_act": has_suggestions and has_writable_context and roi_defined,
        "reject_visible_suggestions_act": has_suggestions and has_writable_context,
        "clear_suggestions_act": has_suggestions, "show_suggestion_patch_act": has_suggestions,
        "show_all_predictions_act": has_suggestions, "toggle_suggestions_overlay_act": has_image,
        "start_timed_session_assisted_act": has_image, "start_timed_session_manual_act": has_image,
        "stop_timed_session_act": bool(getattr(owner, "_timed_session_active", False)),
        "assist_warmup_act": can_assist, "train_ranker_now_act": has_annotations,
        "show_calibration_visualizer_act": has_annotations,
        "batch_correct_suggestions_act": has_suggestions and has_writable_context,
        "propagate_suggestions_act": has_suggestions and has_writable_context,
        "set_current_user_act": can_review, "mark_selected_in_review_act": selection_count > 0,
        "mark_selected_approved_act": selection_count > 0,
        "mark_selected_needs_changes_act": selection_count > 0,
        "assign_selected_act": selection_count > 0,
        "show_reviewer_analytics_act": has_annotations,
        "queue_all_act": can_review, "queue_my_act": can_review,
        "queue_needs_review_act": can_review, "queue_blocked_qc_act": has_qc,
        "qc_validate_act": has_annotations, "qc_jump_next_act": has_qc,
        "review_context_pack_act": can_review, "jump_to_frame_act": has_image,
        "jump_to_z_act": has_image, "focus_canvas_mode_act": has_image,
        "advanced_panels_act": True, "open_panel_policy_act": True,
        "toggle_profile_act": has_image, "toggle_hist_act": has_image,
        "toggle_left_act": True, "toggle_settings_act": True,
        "toggle_overlay_act": has_image, "save_layout_act": True,
        "undo_layout_change_act": bool(getattr(owner, "_layout_history", None)),
        "save_layout_default_act": True, "reset_layout_act": True,
        "link_zoom_act": has_image, "show_roi_handles_act": has_image,
        "show_recorder_act": has_image, "threshold_act": has_image,
        "analyze_particles_act": has_image, "smlm_act": roi_defined,
        "deepstorm_act": roi_defined,
        "rerun_smlm_act": bool(getattr(owner, "_last_smlm_run_config", None)),
        "reset_view_act": has_image, "toggle_logs_act": True,
    }


def build_action_disabled_reason() -> dict[str, str]:
    """Build static disabled-reason text for status-driven actions."""
    return {
        "load_ann_current_act": "Load an image or select a target context first.",
        "load_ann_all_act": "Load an image set before loading all linked annotations.",
        "reload_ann_act": "Load an image before reloading annotations.",
        "save_proj_act": "Open data before saving a project workspace.",
        "save_csv_act": "Saving annotations requires a writable annotation context.",
        "save_json_act": "Saving annotations requires a writable annotation context.",
        "export_view_act": "Load an image before exporting the current view.",
        "copy_display_act": "Load an image before copying display settings.",
        "measure_act": "Add annotations or define an ROI before measuring.",
        "clear_roi_act": "Define an ROI before clearing it.",
        "copy_roi_to_all_act": "Define an ROI before propagating it.",
        "save_roi_template_act": "Define an ROI before saving it as a template.",
        "apply_roi_template_act": "Load an image before applying an ROI template.",
        "suggest_points_act": "Suggestion generation requires a writable annotation target.",
        "suggest_points_image_act": "Suggestion generation requires a writable annotation target.",
        "select_suggestion_strategy_act": "Load an image before changing the suggestion strategy.",
        "load_suggestion_rule_config_act": "Load an image before loading a suggestion rule configuration.",
        "set_suggestion_score_threshold_act": "Load an image before changing the suggestion threshold.",
        "accept_visible_suggestions_act": "Visible suggestions and a writable target are required.",
        "accept_green_suggestions_act": "Visible suggestions and a writable target are required.",
        "accept_suggestions_in_roi_act": "Visible suggestions, a writable target, and an ROI are required.",
        "reject_visible_suggestions_act": "Visible suggestions and a writable target are required.",
        "clear_suggestions_act": "There are no suggestions to clear.",
        "show_suggestion_patch_act": "There are no suggestions to inspect.",
        "show_all_predictions_act": "There are no suggestions to inspect.",
        "toggle_suggestions_overlay_act": "Load an image before toggling suggestion overlays.",
        "stop_timed_session_act": "No timed session is currently running.",
        "assist_warmup_act": "Warmup requires a writable annotation target.",
        "train_ranker_now_act": "Training requires existing annotations.",
        "show_calibration_visualizer_act": "Calibration requires existing annotations.",
        "batch_correct_suggestions_act": "Visible suggestions and a writable target are required.",
        "propagate_suggestions_act": "Visible suggestions and a writable target are required.",
        "set_current_user_act": "Review actions require existing annotations.",
        "mark_selected_in_review_act": "Select one or more annotations first.",
        "mark_selected_approved_act": "Select one or more annotations first.",
        "mark_selected_needs_changes_act": "Select one or more annotations first.",
        "assign_selected_act": "Select one or more annotations first.",
        "show_reviewer_analytics_act": "Reviewer analytics require existing annotations.",
        "queue_all_act": "Review queue filters require existing annotations.",
        "queue_my_act": "Review queue filters require existing annotations.",
        "queue_needs_review_act": "Review queue filters require existing annotations.",
        "queue_blocked_qc_act": "No QC-blocked annotations are currently available.",
        "qc_validate_act": "QC validation requires existing annotations.",
        "qc_jump_next_act": "There are no QC issues to review.",
        "review_context_pack_act": "Review context requires existing annotations.",
        "jump_to_frame_act": "Load an image before navigating frames.",
        "jump_to_z_act": "Load an image before navigating Z slices.",
        "focus_canvas_mode_act": "Load an image before enabling canvas focus mode.",
        "toggle_profile_act": "Load an image before showing line profiles.",
        "toggle_hist_act": "Load an image before showing histograms.",
        "toggle_overlay_act": "Load an image before toggling overlays.",
        "link_zoom_act": "Load an image before linking synced views.",
        "show_roi_handles_act": "Load an image before showing ROI handles.",
        "show_recorder_act": "Load an image before opening the recorder.",
        "threshold_act": "Load an image before opening threshold controls.",
        "analyze_particles_act": "Load an image before analyzing particles.",
        "smlm_act": "Define an ROI before running ThunderSTORM.",
        "deepstorm_act": "Define an ROI before running Deep-STORM.",
        "rerun_smlm_act": "Run an SMLM workflow once before rerunning it.",
        "reset_view_act": "Load an image before resetting the canvas view.",
    }
