"""Density prediction panel widgets."""

from __future__ import annotations

from matplotlib.backends.qt_compat import QtCore, QtWidgets


class DensityPanel(QtWidgets.QWidget):
    """Dock widget for density model inference controls."""

    def __init__(self, parent: QtWidgets.QWidget | None = None) -> None:
        super().__init__(parent)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(8)

        model_group = QtWidgets.QGroupBox("Model")
        model_layout = QtWidgets.QGridLayout(model_group)
        self.model_path_edit = QtWidgets.QLineEdit()
        self.model_browse_btn = QtWidgets.QPushButton("Browse")
        self.device_combo = QtWidgets.QComboBox()
        self.device_combo.addItems(["auto", "cpu", "cuda"])
        self.load_btn = QtWidgets.QPushButton("Load model")
        self.model_status = QtWidgets.QLabel("No model loaded.")
        model_layout.addWidget(QtWidgets.QLabel("Model file"), 0, 0)
        model_layout.addWidget(self.model_path_edit, 0, 1)
        model_layout.addWidget(self.model_browse_btn, 0, 2)
        model_layout.addWidget(QtWidgets.QLabel("Device"), 1, 0)
        model_layout.addWidget(self.device_combo, 1, 1)
        model_layout.addWidget(self.load_btn, 1, 2)
        model_layout.addWidget(self.model_status, 2, 0, 1, 3)

        input_group = QtWidgets.QGroupBox("Input")
        input_layout = QtWidgets.QGridLayout(input_group)
        self.target_combo = QtWidgets.QComboBox()
        self.target_combo.addItems(["Frame", "Mean", "Composite", "Support"])
        self.scope_combo = QtWidgets.QComboBox()
        self.scope_combo.addItems(["Current slice"])
        self.roi_only_chk = QtWidgets.QCheckBox("ROI only")
        self.roi_only_chk.setChecked(True)
        input_layout.addWidget(QtWidgets.QLabel("Target panel"), 0, 0)
        input_layout.addWidget(self.target_combo, 0, 1)
        input_layout.addWidget(QtWidgets.QLabel("Scope"), 1, 0)
        input_layout.addWidget(self.scope_combo, 1, 1)
        input_layout.addWidget(self.roi_only_chk, 2, 0, 1, 2)

        preprocess_group = QtWidgets.QGroupBox("Preprocess")
        preprocess_layout = QtWidgets.QGridLayout(preprocess_group)
        self.normalize_combo = QtWidgets.QComboBox()
        self.normalize_combo.addItems(["percentile", "zscore", "minmax"])
        self.p_low_spin = QtWidgets.QDoubleSpinBox()
        self.p_low_spin.setRange(0.0, 50.0)
        self.p_low_spin.setValue(1.0)
        self.p_high_spin = QtWidgets.QDoubleSpinBox()
        self.p_high_spin.setRange(50.0, 100.0)
        self.p_high_spin.setValue(99.0)
        self.invert_chk = QtWidgets.QCheckBox("Invert")
        preprocess_layout.addWidget(QtWidgets.QLabel("Normalize"), 0, 0)
        preprocess_layout.addWidget(self.normalize_combo, 0, 1)
        preprocess_layout.addWidget(QtWidgets.QLabel("p_low"), 1, 0)
        preprocess_layout.addWidget(self.p_low_spin, 1, 1)
        preprocess_layout.addWidget(QtWidgets.QLabel("p_high"), 2, 0)
        preprocess_layout.addWidget(self.p_high_spin, 2, 1)
        preprocess_layout.addWidget(self.invert_chk, 3, 0, 1, 2)

        infer_group = QtWidgets.QGroupBox("Inference")
        infer_layout = QtWidgets.QGridLayout(infer_group)
        self.tile_spin = QtWidgets.QSpinBox()
        self.tile_spin.setRange(64, 1024)
        self.tile_spin.setValue(256)
        self.overlap_spin = QtWidgets.QSpinBox()
        self.overlap_spin.setRange(0, 256)
        self.overlap_spin.setValue(32)
        self.batch_spin = QtWidgets.QSpinBox()
        self.batch_spin.setRange(1, 64)
        self.batch_spin.setValue(8)
        self.run_btn = QtWidgets.QPushButton("Run")
        self.cancel_btn = QtWidgets.QPushButton("Cancel")
        self.cancel_btn.setEnabled(False)
        infer_layout.addWidget(QtWidgets.QLabel("Tile size"), 0, 0)
        infer_layout.addWidget(self.tile_spin, 0, 1)
        infer_layout.addWidget(QtWidgets.QLabel("Overlap"), 1, 0)
        infer_layout.addWidget(self.overlap_spin, 1, 1)
        infer_layout.addWidget(QtWidgets.QLabel("Batch tiles"), 2, 0)
        infer_layout.addWidget(self.batch_spin, 2, 1)
        infer_layout.addWidget(self.run_btn, 3, 0)
        infer_layout.addWidget(self.cancel_btn, 3, 1)

        output_group = QtWidgets.QGroupBox("Output")
        output_layout = QtWidgets.QGridLayout(output_group)
        self.count_total_label = QtWidgets.QLabel("Total: -")
        self.count_roi_label = QtWidgets.QLabel("ROI: -")
        self.overlay_chk = QtWidgets.QCheckBox("Show density overlay")
        self.overlay_alpha = QtWidgets.QDoubleSpinBox()
        self.overlay_alpha.setRange(0.0, 1.0)
        self.overlay_alpha.setSingleStep(0.05)
        self.overlay_alpha.setValue(0.6)
        self.overlay_cmap = QtWidgets.QComboBox()
        self.overlay_cmap.addItems(["magma", "viridis", "plasma", "inferno"])
        self.contours_chk = QtWidgets.QCheckBox("Show contours")
        self.export_map_btn = QtWidgets.QPushButton("Save density map")
        self.export_counts_btn = QtWidgets.QPushButton("Save counts CSV")
        output_layout.addWidget(self.count_total_label, 0, 0)
        output_layout.addWidget(self.count_roi_label, 0, 1)
        output_layout.addWidget(self.overlay_chk, 1, 0, 1, 2)
        output_layout.addWidget(QtWidgets.QLabel("Alpha"), 2, 0)
        output_layout.addWidget(self.overlay_alpha, 2, 1)
        output_layout.addWidget(QtWidgets.QLabel("LUT"), 3, 0)
        output_layout.addWidget(self.overlay_cmap, 3, 1)
        output_layout.addWidget(self.contours_chk, 4, 0, 1, 2)
        output_layout.addWidget(self.export_map_btn, 5, 0)
        output_layout.addWidget(self.export_counts_btn, 5, 1)

        layout.addWidget(model_group)
        layout.addWidget(input_group)
        layout.addWidget(preprocess_group)
        layout.addWidget(infer_group)
        layout.addWidget(output_group)
        layout.addStretch(1)
