"""Application settings keys and default values."""

from __future__ import annotations

# UI/window settings

WINDOW_GEOMETRY = "window_geometry"
WINDOW_STATE = "window_state"
DEFAULT_LAYOUT_PRESET = "defaultLayoutPreset"
LAST_OPEN_FOLDER = "lastOpenFolder"

# Display/rendering settings

MARKER_SIZE = "markerSize"
MARKER_SIZE_DEFAULT = 40

CLICK_RADIUS_PX = "clickRadiusPx"
CLICK_RADIUS_PX_DEFAULT = 6.0

DEFAULT_COLORMAP = "defaultColormap"
DEFAULT_COLORMAP_DEFAULT = "viridis"

DOWNSAMPLE_FACTOR = "downsampleFactor"
DOWNSAMPLE_FACTOR_DEFAULT = 2  # INTERACTIVE_DOWNSAMPLE

DOWNSAMPLE_IMAGES = "downsampleImages"
DOWNSAMPLE_IMAGES_DEFAULT = True

DOWNSAMPLE_HIST = "downsampleHist"
DOWNSAMPLE_HIST_DEFAULT = True

DOWNSAMPLE_PROFILE = "downsampleProfile"
DOWNSAMPLE_PROFILE_DEFAULT = True

# Pixel size and scale bar settings

DEFAULT_PIXEL_SIZE_UM_PER_PX = "defaultPixelSizeUmPerPx"
DEFAULT_PIXEL_SIZE_UM_PER_PX_DEFAULT = 0.069

SCALE_BAR_ENABLED = "scaleBarEnabled"
SCALE_BAR_ENABLED_DEFAULT = False

SCALE_BAR_LENGTH_UM = "scaleBarLengthUm"
SCALE_BAR_LENGTH_UM_DEFAULT = 5.0

SCALE_BAR_THICKNESS_PX = "scaleBarThicknessPx"
SCALE_BAR_THICKNESS_PX_DEFAULT = 4

SCALE_BAR_LOCATION = "scaleBarLocation"
SCALE_BAR_LOCATION_DEFAULT = "bottom_right"

SCALE_BAR_PADDING_PX = "scaleBarPaddingPx"
SCALE_BAR_PADDING_PX_DEFAULT = 12

SCALE_BAR_SHOW_TEXT = "scaleBarShowText"
SCALE_BAR_SHOW_TEXT_DEFAULT = True

SCALE_BAR_TEXT_OFFSET_PX = "scaleBarTextOffsetPx"
SCALE_BAR_TEXT_OFFSET_PX_DEFAULT = 6

SCALE_BAR_BACKGROUND_BOX = "scaleBarBackgroundBox"
SCALE_BAR_BACKGROUND_BOX_DEFAULT = True

SCALE_BAR_INCLUDE_IN_EXPORT = "scaleBarIncludeInExport"
SCALE_BAR_INCLUDE_IN_EXPORT_DEFAULT = True

# Cache/performance settings

CACHE_MAX_MB = "cacheMaxMB"
CACHE_MAX_MB_DEFAULT = 1024

PYRAMID_ENABLED = "pyramidEnabled"
PYRAMID_ENABLED_DEFAULT = False

PYRAMID_MAX_LEVELS = "pyramidMaxLevels"
PYRAMID_MAX_LEVELS_DEFAULT = 3

PREFETCH_BLOCK_SIZE_FRAMES = "prefetchBlockSizeFrames"
PREFETCH_BLOCK_SIZE_FRAMES_DEFAULT = 64

# ROI/annotation settings

SHOW_ROI_HANDLES = "showRoiHandles"
SHOW_ROI_HANDLES_DEFAULT = True

# Flat map for key->default lookups

DEFAULTS = {
    # Window settings
    WINDOW_GEOMETRY: None,
    WINDOW_STATE: None,
    DEFAULT_LAYOUT_PRESET: "default",
    LAST_OPEN_FOLDER: "",
    
    # Display settings
    MARKER_SIZE: MARKER_SIZE_DEFAULT,
    CLICK_RADIUS_PX: CLICK_RADIUS_PX_DEFAULT,
    DEFAULT_COLORMAP: DEFAULT_COLORMAP_DEFAULT,
    DOWNSAMPLE_FACTOR: DOWNSAMPLE_FACTOR_DEFAULT,
    DOWNSAMPLE_IMAGES: DOWNSAMPLE_IMAGES_DEFAULT,
    DOWNSAMPLE_HIST: DOWNSAMPLE_HIST_DEFAULT,
    DOWNSAMPLE_PROFILE: DOWNSAMPLE_PROFILE_DEFAULT,
    
    # Pixel size & scale bar
    DEFAULT_PIXEL_SIZE_UM_PER_PX: DEFAULT_PIXEL_SIZE_UM_PER_PX_DEFAULT,
    SCALE_BAR_ENABLED: SCALE_BAR_ENABLED_DEFAULT,
    SCALE_BAR_LENGTH_UM: SCALE_BAR_LENGTH_UM_DEFAULT,
    SCALE_BAR_THICKNESS_PX: SCALE_BAR_THICKNESS_PX_DEFAULT,
    SCALE_BAR_LOCATION: SCALE_BAR_LOCATION_DEFAULT,
    SCALE_BAR_PADDING_PX: SCALE_BAR_PADDING_PX_DEFAULT,
    SCALE_BAR_SHOW_TEXT: SCALE_BAR_SHOW_TEXT_DEFAULT,
    SCALE_BAR_TEXT_OFFSET_PX: SCALE_BAR_TEXT_OFFSET_PX_DEFAULT,
    SCALE_BAR_BACKGROUND_BOX: SCALE_BAR_BACKGROUND_BOX_DEFAULT,
    SCALE_BAR_INCLUDE_IN_EXPORT: SCALE_BAR_INCLUDE_IN_EXPORT_DEFAULT,
    
    # Cache & performance
    CACHE_MAX_MB: CACHE_MAX_MB_DEFAULT,
    PYRAMID_ENABLED: PYRAMID_ENABLED_DEFAULT,
    PYRAMID_MAX_LEVELS: PYRAMID_MAX_LEVELS_DEFAULT,
    PREFETCH_BLOCK_SIZE_FRAMES: PREFETCH_BLOCK_SIZE_FRAMES_DEFAULT,
    
    # ROI & annotations
    SHOW_ROI_HANDLES: SHOW_ROI_HANDLES_DEFAULT,
}


def get_default(key: str, fallback=None):
    """Return the configured default for a settings key."""
    return DEFAULTS.get(key, fallback)
